<form id="login" enctype="application/x-www-form-urlencoded" method="post" action="/auth/anonymous<?=$this->next?>"><dl class="zend_form">
<dt id="username-label"><label for="name" class="required">Vardas:</label></dt>
<dd id="username-element">
<input type="text" name="name" id="tel" value="" /></dd>

<dt id="password-label"><label for="tel" class="required">Telefonas:</label></dt>
<dd id="password-element">
<input type="text" name="tel" id="tel" value="" /></dd>

<dt id="password-label"><label for="email" class="required">El. paštas:</label></dt>
<dd id="password-element">
<input type="text" name="email" id="email" value="" /></dd>

<dt id="password-label"><label for="other" class="required">Kita informacija:</label></dt>
<dd id="password-element">
<input type="text" name="other" id="other" value="" /></dd>


<dt id="login-label">&#160;</dt><dd id="login-element">
<input type="submit" name="request" id="request" value="Išsiųsti" /></dd></dl></form> 
