<?=$this->form->setAction($this->url());?>

<?php if(isset($this->next)):?>
<a href="#continue_anonymous" role="button" class="btn-anonymous" data-toggle="modal">Tęsti neprisijungus</a>
<script type="text/javascript">
    $(document).ready(function() {
     $(".btn-anonymous").click(function(){
        $('.login-content').load('/default/auth/anonymous<?=$this->next?>/format/html/');
     });
    });
</script>  
<?php endif; ?>
