<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="https://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="765" height="350" id="komentarai765x350_swf" align="middle">
            <param name="allowScriptAccess" value="sameDomain" />
            <param name="allowFullScreen" value="false" />
            <param name="movie" value="UserFiles/Banner/komentarai765x350.swf?xml_file=UserFiles/Banner/xml/nqpj4fpjkapfg0mifrnmu5cm_data.xml&sec=27" />
            <param name="wmode" value="transparent" />
            <param name="quality" value="high" />
            <param name="bgcolor" value="#ffffff" />
            <embed src="https://www.manoteo.lt/UserFiles/Banner/komentarai765x350.swf?xml_file=https://www.manoteo.lt/UserFiles/Banner/xml/nqpj4fpjkapfg0mifrnmu5cm_data.xml&sec=27" quality="high" bgcolor="#ffffff" wmode="transparent" width="765" height="350" name="komentarai765x350_swf" align="middle" allowscriptaccess="sameDomain" allowfullscreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />
</object>

<h2>Testavimui naudoti <?=$this->a?></h2>

<img src="/getservice.png">
