<!DOCTYPE html>
<html>
  <head>
    <title>ManoTEO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/styles/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/styles/mt.css" rel="stylesheet" media="screen">
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/styles/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "div.editable",
            inline: true,
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        });
    </script>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    
    
  </head>
  <body>
    
        <!-- Login Modal -->
        <div id="login" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Prisijungti</h3>
            </div>
        <div class="modal-body">
            <p class="login-content"></p>
                       
        </div>
      </div>
    
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            
         
            
            <a class="brand" href="<?= $this->url(array('action'=>'index','controller'=>'index'));?>"><img src="/top_menu_teo_logo.gif" ></a>
            <div class="nav-collapse collapse">
              <p class="navbar-text pull-right" style="padding-top:5px;">
                <?php if(isset($this->username)):?>
                Jūs prisijungęs kaip: <a href="#" class="navbar-link"><?=$this->username;?></a>
                <a href="<?= $this->url(array('action'=>'logout','controller'=>'auth')); ?>" style="color:#fff;">atsijungti</a>
                <?php else: ?>
                <a href="<?= $this->url(array('action'=>'index','controller'=>'auth')); ?>" style="color:#fff;">prisijungti</a>
                <?php endif; ?>
              </p>
              <ul class="nav" >
                <li><a href="<?= $this->url(array('action'=>'index','controller'=>'services')); ?>" style="padding-top:15px;">Mano paslaugos</a></li>
                <li><a href="<?= $this->url(array('action'=>'history','controller'=>'bills')); ?>" style="padding-top:15px;">Sąskaitos</a></li>
              </ul>
            </div><!--/.nav-collapse -->
         </div>
        </div>
      </div>
    
      <div class="container-fluid" style="top:70px; position:absolute;">     
          <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <?php echo $this->navigation()->menu()->setMinDepth(1); ?>
	            </div><!--/.well -->
	            <p><a  href="<?= $this->url(array('action'=>'index','controller'=>'bills'));?>">sugeneruoti 300K SQL sąskaitų</a></p>
	            <p><a  href="<?= $this->url(array('action'=>'generatemessages','controller'=>'rabbit'));?>">sugeneruoti Rabbit žinutes</a></p>
	            <p><a  href="<?= $this->url(array('action'=>'handlebillevents','controller'=>'rabbit'));?>">apdoroti Rabbit žinutes (bill)</a></p>
	            <p><a  href="<?= $this->url(array('action'=>'handleserviceevents','controller'=>'rabbit'));?>">apdoroti Rabbit žinutes (service)</a></p>
                <p><a  href="<?= $this->url(array('action'=>'count','controller'=>'bills'));?>">sąskaitų skaičius</a></p>
	            <p><a  href="<?= $this->url(array('action'=>'listrequests','controller'=>'auth'));?>">anoniminiai paklausimai</a></p>
            </div><!--/span-->

            <div class="span7">

                
                <?php if(isset($this->user) and $this->user['category'] <= $this->content['category']):?>
                    <div class="grey-rounded-block-1">
                        <form id="edit-form" method="post" action="<?= $this->url(array('action'=>'edit','controller'=>'services'));?>"><fieldset>
                            <div class="editable" style="width:100%">
                                <?=$this->content['body'];?>
                            </div>
                            <div>
                                <a class="btn submitbtn" id="edit-text" href="#"><img src="/save.png"></a>
                            </div>
                                <script type="text/javascript">
                                  $(document).ready(function() {
                                     $("#edit-text").click(function(){
                                    	 $('#edit-form').submit();
                                     });
                                  });
                                </script>
                                <input type="hidden" name="uri" id="uri" value="<?=$this->url();?>" />
                                <input type="hidden" name="category" id="category" value="<?=max($this->user['category'],$this->content['category']);?>" />
                        </fieldset></form>
                    </div>
                <?php elseif(isset($this->content['body'])):?>
                    <div class="grey-rounded-block-1">
                        <?=$this->content['body'];?>
                    </div>
                <?php endif;?>           
            
                <?php echo $this->layout()->content; ?>	
            </div>
         </div>
      
   
        <footer style="padding-left: 90px;">
        <img src="/footer.png">
        </footer>

      </div><!--/.fluid-container-->

  
  </body>
</html>
