<!DOCTYPE html>
<html>
  <head>
    <title>ManoTEO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/styles/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/styles/bootstrap/js/bootstrap.min.js"></script>
    
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    
    
  </head>
  <body>
      
      <div class="container-fluid">
          <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <?php echo $this->navigation()->menu()->setMinDepth(1); ?>
                    <?php //echo $this->navigation()->breadcrumbs()->setMinDepth(1)->setLinkLast(true)->setSeparator(" : "); ?>
	            </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
                <?php echo $this->layout()->content; ?>	
            </div>
         </div>
      </div>
   
    <p>Login <a href="<?= $this->url(array('action'=>'index','controller'=>'auth')); ?>">login</a></p>

      <footer>
      </footer>

    </div><!--/.fluid-container-->

  
  </body>
</html>
