<!DOCTYPE html>
<html>
  <head>
    <title>ManoTEO</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="/styles/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="/styles/bootstrap/js/bootstrap.min.js"></script>
  </head>
  <body>
	<?php echo $this->layout()->content; ?>	
  </body>
</html>