
<table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Data</th>
                <th colspan="2">Mokėjimai / Sąskaitos</th>
                <th>Laikotarpis</th>
                <th>Suma</th>
                <th colspan="2">Skambučių sąrašas</th>
              </tr>
            </thead>
            <tbody>
            <? foreach ($this->bills as $bill): ?>
              <tr>
                <td><?=$bill['date'];?></td>
                <td><?=$bill['type'];?></td>
                <td><?=$bill['doc'];?></td>
                <td><?=$bill['period'];?></td>
                <td><?=$bill['amount'];?></td>
                <td><?=$bill['report'];?></td>
                <td><?=$bill['paid'];?></td>
              </tr>
            <? endforeach; ?>
            </tbody>
          </table>
